default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  <<: *default
  database: mayby_aws_development

test:
  <<: *default
  database: mayby_aws_test

production:
  <<: *default
  database: mayby_aws_production
  username: mayby_aws_app
  password: <%= ENV['MAYBY_AWS_DATABASE_PASSWORD'] %>